#!/usr/bin/env bash

# Define color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

exec_link_path="$HOME/.local/bin" # Updated to user-specific bin directory

# Function to print messages
print_message() {
    local color=$1
    local message=$2
    echo -e "${color}${message}${NC}"
}

# Detect user shell and set dotFile
detect_shell() {
    local user_shell=$SHELL
    print_message "$GREEN" "Detected shell: $user_shell"

    if [[ $user_shell == */bash ]]; then
        dotFile="$HOME/.bashrc"
    elif [[ $user_shell == */zsh ]]; then
        dotFile="$HOME/.zshrc"
    else
        print_message "$RED" "Unsupported shell: $user_shell"
        exit 1
    fi
}

# Remove symbolic link
remove_symlink() {
    if [ -L "$exec_link_path/bro" ]; then
        if rm "$exec_link_path/bro"; then
            print_message "$GREEN" "bro has been successfully removed from $exec_link_path ✅"
        else
            print_message "$RED" "Failed to remove bro from $exec_link_path."
        fi
    else
        print_message "$RED" "bro is not installed in $exec_link_path."
    fi
}

# Remove GROQ_API_KEY from dotFile
remove_api_key() {
    if [ -f "$dotFile" ]; then
        if grep -q "export GROQ_API_KEY" "$dotFile"; then
            sed -i "/export GROQ_API_KEY/d" "$dotFile"
            print_message "$GREEN" "GROQ_API_KEY has been removed from $dotFile ✅"
        else
            print_message "$YELLOW" "GROQ_API_KEY is not set in $dotFile."
        fi
    else
        print_message "$RED" "$dotFile does not exist."
    fi
}

# Remove node_modules folder
remove_node_modules() {
    if [ -d "node_modules" ]; then
        rm -rf node_modules
        print_message "$GREEN" "node_modules folder has been removed ✅"
    else
        print_message "$RED" "node_modules folder does not exist."
    fi
}

# Remove bun.lockb file
remove_bun_lockb() {
    if [ -f "bun.lockb" ]; then
        rm bun.lockb
        print_message "$GREEN" "bun.lockb file has been removed ✅"
    else
        print_message "$RED" "bun.lockb file does not exist."
    fi
}

# Main script execution
detect_shell
remove_symlink
remove_api_key
remove_node_modules
remove_bun_lockb